version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export AWS_DEFAULT_REGION=us-east-1
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hiqode-app
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started...
      - docker build -t hiqode-app .
      - docker tag hiqode-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Build completed successfully!
